import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import { useState } from "react";

// const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  // const [navbar, setNavbar] = useState(false);
  return (
    <div>
      <Head>
        <title>Favela Your Property at One Click</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/assets/logo/properti.png" />
      </Head>
      <nav className="mx-auto font-poppins bg-white shadow text-xl pt-16 pb-10 px-28 text-black">
        <div className="flex justify-between">
          <div className="flex items-center">
            <img src="/assets/logo/properti.png" className="w-9 h-9" />
            <p className="font-poppins font-bold">FAVELA</p>
          </div>
          <div className="flex space-x-16 items-center">
            <div className="space-x-16">
              <a className="border-b-[2.5px] border-black" href="#">
                Home
              </a>
              <a className="nav-button-hover" href="#">
                Order
              </a>
              <a className="nav-button-hover" href="#">
                About
              </a>
              <a className="nav-button-hover" href="#">
                Contact
              </a>
            </div>
            <div>
              <img src="assets/profile/avatar.jpg" alt="" className="w-9 h-9 rounded-full"></img>
            </div>
          </div>
        </div>
        {/* mobile nav */}
      </nav>
      <div className="items-center m-8 pt-28 bg-white ">
        <p className="text-2xl text-justify font-bold text-black font-poppins">
          Lorem ipsum dolor sit amet consectetur adipisicing elit. Ratione,
          magni sapiente? Possimus quod porro nemo deleniti maxime non ullam
          exercitationem totam voluptates sit, commodi voluptatum repellat neque
          vero eius nostrum unde et tempora. Sint consectetur ea, consequatur
          assumenda ipsum laboriosam tenetur minima natus dolore labore officia
          praesentium obcaecati est. Magnam?
        </p>
      </div>
    </div>
  );
}
