import Head from "next/head";
import Navbar from "./navbar";
import Image from "next/image";
import { Inter } from "next/font/google";
import { useState } from "react";
import Footer from "./footer";

// const inter = Inter({ subsets: ["latin"] });

export default function Product() {
   // const [navbar, setNavbar] = useState(false);
   return (
      <div>
         <Head>
            <title>Favela Your Property at One Click</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/assets/logo/properti.png" />
         </Head>
         <Navbar></Navbar>
         <div className="bg-white">
            asdasdasdasd
            <br></br>
            <br></br>
            <br></br>
            <br></br>
            <br></br>
            <br></br>
            <br></br>
            <br></br>
            <br></br>
            <br></br>
            <br></br>
            <br></br>
            <br></br>
            <br></br>
            <br></br>
            <br></br>
            <br></br>
            <br></br>
            <br></br>
            <br></br>
            <br></br>
            <br></br>
            <br></br>
            <br></br>
            <br></br>
            <br></br>
            <br></br>
            <br></br>
            <br></br>
            <br></br>
            <br></br>
            <br></br>
            <br></br>
            <br></br>
            <br></br>
            <br></br>
            <br></br>
            <br></br>
            <br></br>
            <br></br>
            <br></br>
            <br></br>
            <br></br>
            <br></br>
            <br></br>
            <br></br>
            <br></br>
            <br></br>
         </div>
         <Footer></Footer>
         {/* content - end */}
      </div >
   );
}
